"""add_file_hash_to_research_reports

Revision ID: bf09b29f337d
Revises: 9fc0e073b347
Create Date: 2026-05-26 02:13:20.827384

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bf09b29f337d'
down_revision: Union[str, Sequence[str], None] = '9fc0e073b347'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('research_reports', sa.Column('file_hash', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_research_reports_file_hash'), 'research_reports', ['file_hash'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_research_reports_file_hash'), table_name='research_reports')
    op.drop_column('research_reports', 'file_hash')
    # ### end Alembic commands ###
