"""add_governance_events

Revision ID: c6a17410438c
Revises: d146f2e12981
Create Date: 2026-05-26 00:55:04.699933

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c6a17410438c'
down_revision: Union[str, Sequence[str], None] = 'd146f2e12981'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('governance_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('institution_id', sa.UUID(), nullable=False),
    sa.Column('portfolio_id', sa.UUID(), nullable=False),
    sa.Column('holding_id', sa.UUID(), nullable=True),
    sa.Column('rule_id', sa.UUID(), nullable=True),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('severity', sa.String(length=50), nullable=False),
    sa.Column('details_json', sa.JSON(), nullable=False),
    sa.Column('resolved', sa.Boolean(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', NOW())"), nullable=False),
    sa.ForeignKeyConstraint(['holding_id'], ['holdings.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['rule_id'], ['ips_rules.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
    
    # Enable Row-Level Security (RLS)
    op.execute("ALTER TABLE governance_events ENABLE ROW LEVEL SECURITY;")
    op.execute("ALTER TABLE governance_events FORCE ROW LEVEL SECURITY;")
    
    # Define RLS policy for tenant isolation
    op.execute(
        "CREATE POLICY governance_event_isolation ON governance_events "
        "USING (institution_id = NULLIF(current_setting('app.current_institution_id', true), '')::uuid);"
    )
    
    # Grant permissions to gripper_app non-superuser role (local Docker only)
    op.execute(
        """
        DO $$
        BEGIN
            IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'gripper_app') THEN
                GRANT ALL PRIVILEGES ON TABLE governance_events TO gripper_app;
            END IF;
        END $$;
        """
    )



def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('governance_events')
    # ### end Alembic commands ###
