"""initial_schema

Revision ID: d146f2e12981
Revises: 
Create Date: 2026-05-26 00:42:15.140337

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector



# revision identifiers, used by Alembic.
revision: str = 'd146f2e12981'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('institutions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('tier', sa.String(length=50), server_default='free', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', NOW())"), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('ips_rules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('institution_id', sa.UUID(), nullable=False),
    sa.Column('rule_type', sa.String(length=100), nullable=False),
    sa.Column('threshold', sa.Float(), nullable=False),
    sa.Column('severity', sa.String(length=50), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', NOW())"), nullable=False),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('meetings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('institution_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('meeting_type', sa.String(length=100), nullable=False),
    sa.Column('transcript', sa.String(), nullable=True),
    sa.Column('summary', sa.String(), nullable=True),
    sa.Column('decisions_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', NOW())"), nullable=False),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('portfolios',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('institution_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('benchmark', sa.String(length=255), nullable=True),
    sa.Column('inception_date', sa.DateTime(), nullable=True),
    sa.Column('strategy_type', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', NOW())"), nullable=False),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('institution_id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('external_id', sa.String(length=255), nullable=True),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('graduation_year', sa.Integer(), nullable=True),
    sa.Column('permissions', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', NOW())"), nullable=False),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('holdings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('portfolio_id', sa.UUID(), nullable=False),
    sa.Column('ticker', sa.String(length=50), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('cost_basis', sa.Float(), nullable=False),
    sa.Column('conviction_score', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', NOW())"), nullable=False),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('research_reports',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('institution_id', sa.UUID(), nullable=False),
    sa.Column('uploaded_by', sa.UUID(), nullable=True),
    sa.Column('sector', sa.String(length=100), nullable=False),
    sa.Column('company', sa.String(length=255), nullable=False),
    sa.Column('recommendation', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', NOW())"), nullable=False),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('document_chunks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('institution_id', sa.UUID(), nullable=False),
    sa.Column('report_id', sa.UUID(), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=384), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', NOW())"), nullable=False),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['report_id'], ['research_reports.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###

    # Enable RLS & Force RLS on all tenant-dependent tables
    op.execute("ALTER TABLE users ENABLE ROW LEVEL SECURITY;")
    op.execute("ALTER TABLE users FORCE ROW LEVEL SECURITY;")
    op.execute("ALTER TABLE portfolios ENABLE ROW LEVEL SECURITY;")
    op.execute("ALTER TABLE portfolios FORCE ROW LEVEL SECURITY;")
    op.execute("ALTER TABLE holdings ENABLE ROW LEVEL SECURITY;")
    op.execute("ALTER TABLE holdings FORCE ROW LEVEL SECURITY;")
    op.execute("ALTER TABLE research_reports ENABLE ROW LEVEL SECURITY;")
    op.execute("ALTER TABLE research_reports FORCE ROW LEVEL SECURITY;")
    op.execute("ALTER TABLE document_chunks ENABLE ROW LEVEL SECURITY;")
    op.execute("ALTER TABLE document_chunks FORCE ROW LEVEL SECURITY;")
    op.execute("ALTER TABLE meetings ENABLE ROW LEVEL SECURITY;")
    op.execute("ALTER TABLE meetings FORCE ROW LEVEL SECURITY;")
    op.execute("ALTER TABLE ips_rules ENABLE ROW LEVEL SECURITY;")
    op.execute("ALTER TABLE ips_rules FORCE ROW LEVEL SECURITY;")

    # Define Row-Level Security isolation policies
    op.execute("CREATE POLICY user_isolation ON users USING (institution_id = NULLIF(current_setting('app.current_institution_id', true), '')::uuid);")
    op.execute("CREATE POLICY portfolio_isolation ON portfolios USING (institution_id = NULLIF(current_setting('app.current_institution_id', true), '')::uuid);")
    op.execute("CREATE POLICY holding_isolation ON holdings USING (portfolio_id IN (SELECT id FROM portfolios WHERE institution_id = NULLIF(current_setting('app.current_institution_id', true), '')::uuid));")
    op.execute("CREATE POLICY report_isolation ON research_reports USING (institution_id = NULLIF(current_setting('app.current_institution_id', true), '')::uuid);")
    op.execute("CREATE POLICY chunk_isolation ON document_chunks USING (institution_id = NULLIF(current_setting('app.current_institution_id', true), '')::uuid);")
    op.execute("CREATE POLICY meeting_isolation ON meetings USING (institution_id = NULLIF(current_setting('app.current_institution_id', true), '')::uuid);")
    op.execute("CREATE POLICY rule_isolation ON ips_rules USING (institution_id = NULLIF(current_setting('app.current_institution_id', true), '')::uuid);")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('document_chunks')
    op.drop_table('research_reports')
    op.drop_table('holdings')
    op.drop_table('users')
    op.drop_table('portfolios')
    op.drop_table('meetings')
    op.drop_table('ips_rules')
    op.drop_table('institutions')
    # ### end Alembic commands ###
